# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2cf112ff3595e14ece0ee4556d3d4dc1539b5fcba7d555c43a98fbaf21cb4e0f8d380d1f87f916374c499929c8b2061cee3921c0958b1ba98c304253bc2615

test:
  secret_key_base: bc91072cd22eaf69bb44b5e29219a8396ed0957e1d141a58f0ec65343ee3911ed5578f3919cef0055f52d16676b0da734880f8b9b40326477395af131bdfc581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
